//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SIESC.WEB.consultaCep {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicoCEPSoap", Namespace="http://tempuri.org/")]
    public partial class ServicoCEP : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObterEnderecoPorLogradouroOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterEnderecoPorLogradouroStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterEnderecoPorCEPOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterEnderecoPorCEPStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterEnderecoPorGrandeUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterCidadesPorEstadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterUFsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicoCEP() {
            this.Url = global::SIESC.WEB.Properties.Settings.Default.SIESC_WEB_consultaCep_ServicoCEP;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObterEnderecoPorLogradouroCompletedEventHandler ObterEnderecoPorLogradouroCompleted;
        
        /// <remarks/>
        public event ObterEnderecoPorLogradouroStringCompletedEventHandler ObterEnderecoPorLogradouroStringCompleted;
        
        /// <remarks/>
        public event ObterEnderecoPorCEPCompletedEventHandler ObterEnderecoPorCEPCompleted;
        
        /// <remarks/>
        public event ObterEnderecoPorCEPStringCompletedEventHandler ObterEnderecoPorCEPStringCompleted;
        
        /// <remarks/>
        public event ObterEnderecoPorGrandeUsuarioCompletedEventHandler ObterEnderecoPorGrandeUsuarioCompleted;
        
        /// <remarks/>
        public event ObterCidadesPorEstadoCompletedEventHandler ObterCidadesPorEstadoCompleted;
        
        /// <remarks/>
        public event ObterUFsCompletedEventHandler ObterUFsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObterEnderecoPorLogradouro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Endereco[] ObterEnderecoPorLogradouro(string logradouro, int idCidade, string uf, string numero) {
            object[] results = this.Invoke("ObterEnderecoPorLogradouro", new object[] {
                        logradouro,
                        idCidade,
                        uf,
                        numero});
            return ((Endereco[])(results[0]));
        }
        
        /// <remarks/>
        public void ObterEnderecoPorLogradouroAsync(string logradouro, int idCidade, string uf, string numero) {
            this.ObterEnderecoPorLogradouroAsync(logradouro, idCidade, uf, numero, null);
        }
        
        /// <remarks/>
        public void ObterEnderecoPorLogradouroAsync(string logradouro, int idCidade, string uf, string numero, object userState) {
            if ((this.ObterEnderecoPorLogradouroOperationCompleted == null)) {
                this.ObterEnderecoPorLogradouroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterEnderecoPorLogradouroOperationCompleted);
            }
            this.InvokeAsync("ObterEnderecoPorLogradouro", new object[] {
                        logradouro,
                        idCidade,
                        uf,
                        numero}, this.ObterEnderecoPorLogradouroOperationCompleted, userState);
        }
        
        private void OnObterEnderecoPorLogradouroOperationCompleted(object arg) {
            if ((this.ObterEnderecoPorLogradouroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterEnderecoPorLogradouroCompleted(this, new ObterEnderecoPorLogradouroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObterEnderecoPorLogradouroString", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObterEnderecoPorLogradouroString(string logradouro, int idCidade, string uf, string numero) {
            object[] results = this.Invoke("ObterEnderecoPorLogradouroString", new object[] {
                        logradouro,
                        idCidade,
                        uf,
                        numero});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObterEnderecoPorLogradouroStringAsync(string logradouro, int idCidade, string uf, string numero) {
            this.ObterEnderecoPorLogradouroStringAsync(logradouro, idCidade, uf, numero, null);
        }
        
        /// <remarks/>
        public void ObterEnderecoPorLogradouroStringAsync(string logradouro, int idCidade, string uf, string numero, object userState) {
            if ((this.ObterEnderecoPorLogradouroStringOperationCompleted == null)) {
                this.ObterEnderecoPorLogradouroStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterEnderecoPorLogradouroStringOperationCompleted);
            }
            this.InvokeAsync("ObterEnderecoPorLogradouroString", new object[] {
                        logradouro,
                        idCidade,
                        uf,
                        numero}, this.ObterEnderecoPorLogradouroStringOperationCompleted, userState);
        }
        
        private void OnObterEnderecoPorLogradouroStringOperationCompleted(object arg) {
            if ((this.ObterEnderecoPorLogradouroStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterEnderecoPorLogradouroStringCompleted(this, new ObterEnderecoPorLogradouroStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObterEnderecoPorCEP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Endereco[] ObterEnderecoPorCEP(string cep) {
            object[] results = this.Invoke("ObterEnderecoPorCEP", new object[] {
                        cep});
            return ((Endereco[])(results[0]));
        }
        
        /// <remarks/>
        public void ObterEnderecoPorCEPAsync(string cep) {
            this.ObterEnderecoPorCEPAsync(cep, null);
        }
        
        /// <remarks/>
        public void ObterEnderecoPorCEPAsync(string cep, object userState) {
            if ((this.ObterEnderecoPorCEPOperationCompleted == null)) {
                this.ObterEnderecoPorCEPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterEnderecoPorCEPOperationCompleted);
            }
            this.InvokeAsync("ObterEnderecoPorCEP", new object[] {
                        cep}, this.ObterEnderecoPorCEPOperationCompleted, userState);
        }
        
        private void OnObterEnderecoPorCEPOperationCompleted(object arg) {
            if ((this.ObterEnderecoPorCEPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterEnderecoPorCEPCompleted(this, new ObterEnderecoPorCEPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObterEnderecoPorCEPString", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObterEnderecoPorCEPString(string cep) {
            object[] results = this.Invoke("ObterEnderecoPorCEPString", new object[] {
                        cep});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObterEnderecoPorCEPStringAsync(string cep) {
            this.ObterEnderecoPorCEPStringAsync(cep, null);
        }
        
        /// <remarks/>
        public void ObterEnderecoPorCEPStringAsync(string cep, object userState) {
            if ((this.ObterEnderecoPorCEPStringOperationCompleted == null)) {
                this.ObterEnderecoPorCEPStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterEnderecoPorCEPStringOperationCompleted);
            }
            this.InvokeAsync("ObterEnderecoPorCEPString", new object[] {
                        cep}, this.ObterEnderecoPorCEPStringOperationCompleted, userState);
        }
        
        private void OnObterEnderecoPorCEPStringOperationCompleted(object arg) {
            if ((this.ObterEnderecoPorCEPStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterEnderecoPorCEPStringCompleted(this, new ObterEnderecoPorCEPStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObterEnderecoPorGrandeUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Endereco[] ObterEnderecoPorGrandeUsuario(string usuario, string uf) {
            object[] results = this.Invoke("ObterEnderecoPorGrandeUsuario", new object[] {
                        usuario,
                        uf});
            return ((Endereco[])(results[0]));
        }
        
        /// <remarks/>
        public void ObterEnderecoPorGrandeUsuarioAsync(string usuario, string uf) {
            this.ObterEnderecoPorGrandeUsuarioAsync(usuario, uf, null);
        }
        
        /// <remarks/>
        public void ObterEnderecoPorGrandeUsuarioAsync(string usuario, string uf, object userState) {
            if ((this.ObterEnderecoPorGrandeUsuarioOperationCompleted == null)) {
                this.ObterEnderecoPorGrandeUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterEnderecoPorGrandeUsuarioOperationCompleted);
            }
            this.InvokeAsync("ObterEnderecoPorGrandeUsuario", new object[] {
                        usuario,
                        uf}, this.ObterEnderecoPorGrandeUsuarioOperationCompleted, userState);
        }
        
        private void OnObterEnderecoPorGrandeUsuarioOperationCompleted(object arg) {
            if ((this.ObterEnderecoPorGrandeUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterEnderecoPorGrandeUsuarioCompleted(this, new ObterEnderecoPorGrandeUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObterCidadesPorEstado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Endereco[] ObterCidadesPorEstado(string uf) {
            object[] results = this.Invoke("ObterCidadesPorEstado", new object[] {
                        uf});
            return ((Endereco[])(results[0]));
        }
        
        /// <remarks/>
        public void ObterCidadesPorEstadoAsync(string uf) {
            this.ObterCidadesPorEstadoAsync(uf, null);
        }
        
        /// <remarks/>
        public void ObterCidadesPorEstadoAsync(string uf, object userState) {
            if ((this.ObterCidadesPorEstadoOperationCompleted == null)) {
                this.ObterCidadesPorEstadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterCidadesPorEstadoOperationCompleted);
            }
            this.InvokeAsync("ObterCidadesPorEstado", new object[] {
                        uf}, this.ObterCidadesPorEstadoOperationCompleted, userState);
        }
        
        private void OnObterCidadesPorEstadoOperationCompleted(object arg) {
            if ((this.ObterCidadesPorEstadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterCidadesPorEstadoCompleted(this, new ObterCidadesPorEstadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObterUFs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Endereco[] ObterUFs() {
            object[] results = this.Invoke("ObterUFs", new object[0]);
            return ((Endereco[])(results[0]));
        }
        
        /// <remarks/>
        public void ObterUFsAsync() {
            this.ObterUFsAsync(null);
        }
        
        /// <remarks/>
        public void ObterUFsAsync(object userState) {
            if ((this.ObterUFsOperationCompleted == null)) {
                this.ObterUFsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterUFsOperationCompleted);
            }
            this.InvokeAsync("ObterUFs", new object[0], this.ObterUFsOperationCompleted, userState);
        }
        
        private void OnObterUFsOperationCompleted(object arg) {
            if ((this.ObterUFsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterUFsCompleted(this, new ObterUFsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Endereco {
        
        private string grandeUsuarioField;
        
        private string tipoLogradouroField;
        
        private string logradouroField;
        
        private string bairroField;
        
        private string paridadeField;
        
        private int numeroInicialField;
        
        private int numeroFinalField;
        
        private string cepField;
        
        private string cidadeField;
        
        private string ufField;
        
        private string nomeUFField;
        
        private int cepUnicoField;
        
        private string distritoDeField;
        
        private int chaveLocalidadeField;
        
        /// <remarks/>
        public string GrandeUsuario {
            get {
                return this.grandeUsuarioField;
            }
            set {
                this.grandeUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string TipoLogradouro {
            get {
                return this.tipoLogradouroField;
            }
            set {
                this.tipoLogradouroField = value;
            }
        }
        
        /// <remarks/>
        public string Logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
            }
        }
        
        /// <remarks/>
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        public string Paridade {
            get {
                return this.paridadeField;
            }
            set {
                this.paridadeField = value;
            }
        }
        
        /// <remarks/>
        public int NumeroInicial {
            get {
                return this.numeroInicialField;
            }
            set {
                this.numeroInicialField = value;
            }
        }
        
        /// <remarks/>
        public int NumeroFinal {
            get {
                return this.numeroFinalField;
            }
            set {
                this.numeroFinalField = value;
            }
        }
        
        /// <remarks/>
        public string Cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        public string NomeUF {
            get {
                return this.nomeUFField;
            }
            set {
                this.nomeUFField = value;
            }
        }
        
        /// <remarks/>
        public int CepUnico {
            get {
                return this.cepUnicoField;
            }
            set {
                this.cepUnicoField = value;
            }
        }
        
        /// <remarks/>
        public string DistritoDe {
            get {
                return this.distritoDeField;
            }
            set {
                this.distritoDeField = value;
            }
        }
        
        /// <remarks/>
        public int ChaveLocalidade {
            get {
                return this.chaveLocalidadeField;
            }
            set {
                this.chaveLocalidadeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ObterEnderecoPorLogradouroCompletedEventHandler(object sender, ObterEnderecoPorLogradouroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterEnderecoPorLogradouroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterEnderecoPorLogradouroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Endereco[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Endereco[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ObterEnderecoPorLogradouroStringCompletedEventHandler(object sender, ObterEnderecoPorLogradouroStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterEnderecoPorLogradouroStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterEnderecoPorLogradouroStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ObterEnderecoPorCEPCompletedEventHandler(object sender, ObterEnderecoPorCEPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterEnderecoPorCEPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterEnderecoPorCEPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Endereco[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Endereco[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ObterEnderecoPorCEPStringCompletedEventHandler(object sender, ObterEnderecoPorCEPStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterEnderecoPorCEPStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterEnderecoPorCEPStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ObterEnderecoPorGrandeUsuarioCompletedEventHandler(object sender, ObterEnderecoPorGrandeUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterEnderecoPorGrandeUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterEnderecoPorGrandeUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Endereco[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Endereco[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ObterCidadesPorEstadoCompletedEventHandler(object sender, ObterCidadesPorEstadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterCidadesPorEstadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterCidadesPorEstadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Endereco[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Endereco[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ObterUFsCompletedEventHandler(object sender, ObterUFsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterUFsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterUFsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Endereco[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Endereco[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591